services:
  local-app:
    image: linuxthekernel-dev
    profiles: ["dev"]
    container_name: linuxthekernel-dev
    build:
      dockerfile: ./Dockerfile
    ports:
      - "80:8080"

  app:
    image: linuxthekernel
    profiles: ["prod"]
    container_name: linuxthekernel
    build:
      dockerfile: ./Dockerfile
    ports:
      - "443:443"
    secrets:
      - cert
      - key
    command:
      - "-tls"
      - "-port=443"
      - "-key=/run/secrets/key"
      - "-cert=/run/secrets/cert"

  proxy:
    image: nginx:latest
    profiles: ["prod"]
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: my_proxy
    ports:
      - "80:80"

secrets:
  cert:
    file: /etc/letsencrypt/live/linuxthekernel.io/fullchain.pem
  key: 
    file: /etc/letsencrypt/live/linuxthekernel.io/privkey.pem